use Test::More;
use CtrlNest::Helper::Constants;

# General
is(SUCCESS, 1);
is(INVALID, 0);

is(INVALID_PARAMS, 0xF0000001);
is(SUCCESS_PARAMS, 0xF0000002);

is(INVALID_CHECKBOX,   0xF0000004);
is(CHECKBOX_CHECKED,   'checked');
is(CHECKBOX_UNCHECKED, 'unchecked');

# Access Code
is(ACCESS_CODE_ALLOWED_CHARS, 'ABCDEFGHJKLMNPQRTUVWXYZ2346789');
is(ACCESS_CODE_LENGTH,        8);

is(ACCESS_CODE_TITLE_MIN_LEN, 1);
is(ACCESS_CODE_TITLE_MAX_LEN, 60);

is(ACCESS_CODE_EXPIRES_IN_10_MIN,         '10m');
is(ACCESS_CODE_EXPIRES_IN_30_MIN,         '30m');
is(ACCESS_CODE_EXPIRES_IN_60_MIN,         '60m');
is(ACCESS_CODE_EXPIRES_IN_1_DAY,          '1d');
is(ACCESS_CODE_EXPIRES_IN_7_DAY,          '7d');
is(ACCESS_CODE_EXPIRES_IN_30_DAY,         '30d');
is(ACCESS_CODE_EXPIRES_IN_NEVER,          'never');
is(ACCESS_CODE_EXPIRES_IN_10_MIN_SECONDS, 600);
is(ACCESS_CODE_EXPIRES_IN_30_MIN_SECONDS, 1800);
is(ACCESS_CODE_EXPIRES_IN_60_MIN_SECONDS, 3600);
is(ACCESS_CODE_EXPIRES_IN_1_DAY_SECONDS,  86400);
is(ACCESS_CODE_EXPIRES_IN_7_DAY_SECONDS,  604800);
is(ACCESS_CODE_EXPIRES_IN_30_DAY_SECONDS, 2592000);
is(ACCESS_CODE_EXPIRES_IN_NEVER_SECONDS,  -1);

is(ACCESS_CODE_TYPE_ALL_RIGHTS,         'all_rights');
is(ACCESS_CODE_TYPE_REGISTER,           'register');
is(ACCESS_CODE_TYPE_2FA,                '2fa');
is(ACCESS_CODE_TYPE_ALL_RIGHTS_BITMASK, 1 << 0);
is(ACCESS_CODE_TYPE_REGISTER_BITMASK,   1 << 1);
is(ACCESS_CODE_TYPE_2FA_BITMASK,        1 << 2);

# Auth
is(USERNAME_MIN_LEN, 3);
is(USERNAME_MAX_LEN, 24);

is(PASSWORD_MIN_LEN,  8);
is(PASSWORD_MAX_LEN,  71);
is(PASSWORD_SUBTYPE,  '2b');
is(PASSWORD_COST,     12);
is(PASSWORD_SALT_LEN, 16);

# Session
is(SESSION_TIMEOUT,    3600);
is(SESSION_NOT_FOUND,  'session not found');
is(MAX_LOGIN_ATTEMPTS, 3);

# Users
is(ROLE_SUDO,  'sudo');
is(ROLE_ADMIN, 'admin');
is(ROLE_USER,  'user');

done_testing;
