name: Continuous Integration

# Triggers the workflow on push or pull request
# events but only for the "master" branch
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

  # Allows to run this workflow manually from the Actions tab
  workflow_dispatch:

# This workflow will download all the essential
# tools, build the application and runt the tests
jobs:
  build-and-test:
    runs-on: ubuntu-latest

    # # Setup PostgreSQL
    # services:
    #   postgres:
    #     image: postgres:16
    #     env:
    #       POSTGRES_USER: postgres
    #       POSTGRES_PASSWORD: secret
    #       POSTGRES_DB: ctrl_nest_test
    #     ports:
    #       - 5432:5432
    #     options: >-
    #       --health-cmd pg_isready
    #       --health-interval 10s
    #       --health-timeout 5s
    #       --health-retries 5

    # # Environment variables for db testing
    env:
      DBI_DSN: dbi:Pg:dbname=ctrl_nest_test;host=localhost;port=5432
      DBI_USER: postgres
      DBI_PASS: secret

    steps:
      # Checks-out the repository under $GITHUB_WORKSPACE
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install Mojo & Carton
        run: |
          sudo apt install build-essential
          sudo apt install cpanminus
          sudo cpanm Mojolicious
          sudo cpanm Carton

      - name: Install Node & NPM
        run: |
          sudo curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo bash -
          sudo apt install nodejs -y

      - name: Install dependencies
        run: |
          carton install

      - name: Run Backend Tests
        run: carton exec -- prove -l t
